### PR TITLE
Create RoomBasedCameraMovement.json

### PR DESCRIPTION
**Pull request by tristanbob**
Added new extension: RoomBasedCameraMovement
Move and zoom camera to the room object that contains the trigger object

Playable game (and source files for example):
https://victrisgames.itch.io/room-based-camera-movement

Video:
https://twitter.com/VictrisGames/status/1447027168135892992

### CODE REVIEW

**Comment by tristanbob** [comment]
This extension already has the ability to implement the same logic as the one made by Jurfix (set lerp=1), so I don't think it makes sense to merge them.

However, I have added Jurfix and Silver-Streak as creators of the extension.

**Comment by arthuro555** [comment]
Ping! Is that extension still being worked on? From what I see there was no upload of an update to the extension after the last review. If no update is posted within 10 days, this submission will be closed.

**Comment by tristanbob** [comment]
Just pushed a commit with:
- Remove parenthesis from sentence
- Renamed "pixels" to "px"
- Removed layer/camera parameters from conditions (they weren't used anyway)

**Comment by tristanbob** [comment]
@Bouh and @arthuro555 do you want anything else changed?  

What is the next step in our process?  Since I created the extension, we should have at least 1 person approve the change.

**Comment by 4ian** [comment]
Let's see if they can review, otherwise ping me and I'll make a review and we can then merge this :)

**Comment by Bouh** [comment]
I tested the extension, it works very well.
I had a doubt about the word `trigger object`.
I thought it was an object to put between the rooms, in fact it is the player. 
It's i guess nice to indicate in the description that this object can be a "Player" `(e.g: Player)`

**Review by Bouh — APPROVED** [review]

**Pull request merged**
