### PR TITLE
AutoTyping: Added multiple functions and a minor fix

### PR DESCRIPTION
**Pull request by tristanbob**
## Changes

- Added an action to skip to end of text
- Added a condition to check when a new character was displayed (to trigger sound effects)
- Added an expression to return the character that was just displayed (to perform conditional logic)
- Before this change, it would always show the first character, even if you paused it at the beginning of the scene.

## Playable game
https://liluo.io/instant-builds/b94cd280-c4a7-4262-bb14-072c8a9c27b3

## Project files
[AutoTyping.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9557419/AutoTyping.zip)

## Video
https://user-images.githubusercontent.com/8879811/189468539-d620bce0-0dc7-40c8-88a5-e5a8e36a5625.mp4

### CODE REVIEW

**Comment by tristanbob** [comment]
I'm done adding functions to this extension.  It is ready for review!  :)

**Comment by Bouh** [comment]
## Extension Best Practices

- [x] Extension Options
- [x] Name
- [x] Versioning
- [x] Descriptions
- [x] Tags
- [x] Help URL
- [x] Extension definitions
- [x] Action and conditions
- [x] Don't use abbreviations
- [x] Affirmative tense
- [x] Be oriented toward everyone not just programmers
- [x] Expressions
- [x] Custom Behaviors
- [x] Events in the extension
- [ ] Variables
 `_write_index` [Variable doesn't use the structure variable (you know the dot)](https://wiki.gdevelop.io/gdevelop5/extensions/best-practices#variables).
- [ ] Timers
   [The timer names are not prefixed :)](https://wiki.gdevelop.io/gdevelop5/extensions/best-practices#timers) `"Autotyping Write Timer"`
- [x] Compatibility
- [ ] Javascript

**Review by Bouh — APPROVED** [review]
I let you take a look at my review and merge.

**Comment by tristanbob** [comment]
> * [ ]  Variables
>   `_write_index` [Variable doesn't use the structure variable (you know the dot)](https://wiki.gdevelop.io/gdevelop5/extensions/best-practices#variables).

This variable name was inherited from the previous version.  I guess I should do what is best, and add a new hidden property instead of an object variable.

> * [ ]  Timers
>   [The timer names are not prefixed :)](https://wiki.gdevelop.io/gdevelop5/extensions/best-practices#timers) `"Autotyping Write Timer"`

Yes, this needs to be renamed.  Thanks!

**Comment by D8H** [comment]
> > * [ ]   Variables
> >   `_write_index` [Variable doesn't use the structure variable (you know the dot)](https://wiki.gdevelop.io/gdevelop5/extensions/best-practices#variables).
> 
> This variable name was inherited from the previous version. I guess I should do what is best, and add a new hidden property instead of an object variable.

It's up to you but scoped variables are ok and it can be changed in one click with a find and replace.
Converting existing variable to properties takes time, it's less time for real improvements.

**Comment by tristanbob** [comment]
I updated the names and then uploaded the project files at the beginning of this PR.

**Pull request merged**
