### PR TITLE
Add ArrayTools extension

### LINKED ISSUE #176: Array tools
## Describe the extension
This adds a lot of of utility functions for working with arrays. It adds the following types of possibilities:
- Combining arrays (concatenate into new array, append all children to another array)
- Finding a value in an array (find index expression, contains condition)
- Reversing arrays
- Get a portion of an array (slice)
- Add and remove lots of children at specific indices at once (fill, splice, shift, pop, add at index)
- Randomness (shuffle children, get a random child)
- Mathematical operations using arrays (sum of all numbers, biggest/smallest number, average number, median number)
- Sort numbers in an array
- String inter-operation (split string into array, join array array children to string)

## Checklist
- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [X] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
I don't have an example file, but I have (arguably) better. Here are some unit tests in a GDevelop project file: 
[arraytools-unit-tests.zip](https://github.com/4ian/GDevelop-extensions/files/6779894/arraytools-unit-tests.zip)

## Extension file
[ArrayTools.zip](https://github.com/4ian/GDevelop-extensions/files/6779897/ArrayTools.zip)

### PR DESCRIPTION
**Pull request by Bouh**
Close #176

# Verification list

- [x] Contains
- [x] Index Of
- [x] Last Index Of
- [x] Flatten
- [x] Splice
- [x] Slice
- [x] Sum
- [ ] Shuffle
- [ ] Reverse
- [ ] Sort
- [x] Min
- [x] Max
- [ ] Join
- [ ] Split
- [ ] Mean
- [ ] Median
- [ ] Get Random Child
- [ ] Fill
- [ ] Concat
- [ ] Append To
- [ ] Pop
- [ ] Shift
- [ ] Insert variable at

### CODE REVIEW

**Comment by arthuro555** [comment]
Personally, I would not make a PR for extensions submitted as issues already as it may duplicate it on the review project and splits the review process. Instead, I would just commit directly on main for issues once the extension is approved.

**Comment by Bouh** [comment]
> Personnellement, je ne ferais pas de PR pour les extensions déjà soumises en tant que problèmes, car cela pourrait le dupliquer sur le projet de révision et diviser le processus de révision. Au lieu de cela, je m'engagerais directement sur les problèmes principaux une fois l'extension approuvée.

Yes I saw that the workflow is changing.
I have to change my habit.

**Review by arthuro555 — APPROVED** [review]
My review has been requested, so I am posting my approval, but obviously since I submitted the extension I consider it in a ready state 🤷‍♂️ .

**Comment by 4ian** [comment]
Consider that you have my approval if everything is tested at least once. Also be sure to double check descriptions for proper english, period at the end of all sentences, simple and quick explanations :)

**Comment by arthuro555** [comment]
> Consider that you have my approval

I'd still wait for Bouh to finish his review, I may have tested everything but having a second opinion on the implementation cannot hurt and may help to identify edge cases or performance loopholes I may have missed.

**Comment by Bouh** [comment]
It looks clean that's ok for me, I'll take a quick look at the tests only then merge tomorrow.

**Comment by 4ian** [comment]
I missed that this was merged, great stuff!! 👍

**Pull request merged**
