### PR TITLE
[Reviewed] [Boids] Use multi-line JS event

### PR DESCRIPTION
**Pull request by D8H**
* Don't show in changelog

### CODE REVIEW

**Comment by arthuro555** [comment]
https://forum.gdevelop.io/t/boids-movement-extansion-bug/43475?u=arthuro555

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by D8H** [comment]
Yes, I'll revert it.

**Comment by D8H** [comment]
JS events and other descriptions seems to work fine so leave them.

**Comment by 4ian** [comment]
At least we're agile! ^^ 

I guess we'll have to wait more... or serialise extension without arrays when they are deployed.

**Pull request merged**
