### PR TITLE
Update gamepad extension 

### PR DESCRIPTION
**Pull request by Bouh**
- Add "Any" to the parameters of the direction for the condition Stick pushed in a direction.
- Change wording to PascalCase for inputs name  (only cosmetic).

### CODE REVIEW

**Comment by Bouh** [comment]
I need you @Silver-Streak & @tristanbob to double check, (I checked on my side)
Tell me if you get a regression with this new version 0.3.0 in an existing project. 
See the changelog in my first post.

**Comment by tristanbob** [comment]
I tested this on an old project and a new one, and it worked great.  

image

**Review by tristanbob — APPROVED** [review]
LGTM!

**Comment by Silver-Streak** [comment]
I use the controller type detection in my main game to determine whether it displays Xbox or PS4 button prompts. I'll test with this and report back if anything behaves oddly.

**Pull request merged**
