### PR TITLE
Switch to a form issue template

### PR DESCRIPTION
**Pull request by arthuro555**
Switches the extension submission template to a [github issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). 
You can find it [live on my fork](https://github.com/arthuro555/GDevelop-extensions/issues/new?assignees=&labels=%E2%9C%A8+New+extension&template=new-extension.yml&title=New+extension%3A+%3Ctitle%3E).

This should allow having a more easy-to-understand and consistent issue submission (allowing to parse them and make them into PRs automatically in the future 👀).

### CODE REVIEW

**Comment by ClementPasteau** [comment]
I was about to suggest using the new Form feature! This should definitely help 👍 👍

**Comment by ClementPasteau** [comment]
One feedback to make sure it doesn't come down to a form ticking again.
Maybe we should improve some lines with examples?
I'm thinking specifically of:
`Extension has a proper name and description` (let's add a `(For example, Name: xxx, Description: yyy)` coming from a good quality extension)
`All behaviors have a description` (let's also add an example description here coming from a nice one?) 

the rest is nice!

**Comment by arthuro555** [comment]
[Updated](https://github.com/GDevelopApp/GDevelop-extensions/blob/b397ec74c0e8687f09985ee9e159f488420b9832/.github/ISSUE_TEMPLATE/new-extension.yml), do you think it is better now?

**Comment by tristanbob** [comment]
When it says "Please enter a link to an example project using your extension." is that expecting the user to host it somewhere?  (or does it let the user upload from their local computer)

**Comment by 4ian** [comment]
Awesome idea to use this form feature!

>  "Please enter a link to an example project using your extension." is that expecting the user to host it somewhere? (or does it let the user upload from their local computer)

Seems that it requires a link, unless there is an option to allow an upload... a Dropbox/GDrive/OneDrive can do the trick but it's a bit less convenient for sure. Not sure if it's blocking or not though.

**Comment by ClementPasteau** [comment]
Sorry I wasn't clear for the first line @arthuro555 

I meant let's add a real name and description for people to get inspired by the quality :)

For instance let's break the check into 2:
`Extension has a clear and concise name (For example, "Sprite Snapshot")`
`Extension has a proper description (For example, "Allows rendering (creating an image) of objects, layers and the scene to display in a sprite. \nThis allows to make optimizations by transforming the resulting image of a shape painter into a faster sprite, or to make viewports/cameras.")`

**Comment by tristanbob** [comment]
> Seems that it requires a link, unless there is an option to allow an upload... a Dropbox/GDrive/OneDrive can do the trick but it's a bit less convenient for sure. Not sure if it's blocking or not though.

This might be a dumb idea, but users could always drag the file into the github issue, which uploads the file, hosts it, and provides a URL that can be pasted into the form.  

```[IsPrime.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7226633/IsPrime.zip)```

**Comment by Bouh** [comment]
Just replace for files fields  **input** by **textarea**
Files can be upload in a textarea only.

**Review by Bouh — APPROVED** [review]
Move on top of the list 
`I've followed the best practices listed on ....`

**Comment by Bouh** [comment]
Also, split, Description into two textarea, where first is the description of the extension, and second is only how we can use it.
Otherwise, people will only write a short description.

Splitting this is two will mandatory people to write something to fill that correctly.
Because I know people are lazy and don't read, they just want send their files.

**Comment by arthuro555** [comment]
[Updated again](https://github.com/GDevelopApp/GDevelop-extensions/blob/reviewing/issue-form/.github/ISSUE_TEMPLATE/new-extension.yml). 

I've done what Bouh asked, and additionally opted for removing most checkboxes to move them over to the best practices page.

**Comment by Bouh** [comment]
It's a great improvement, thank you :D 
LGTM

**Comment by arthuro555** [comment]
Thanks everyone for the helpful comments! I've gone ahead and merged it, feel free to open another PR if you feel something is missing or should be changed.

**Pull request merged**
