### PR TITLE
Add Magnetic Effect extension

### PR DESCRIPTION
**Pull request by ClementPasteau**
Add Magnetic Effect extension suggested in #195 
Reviewed, tested and tweaked some variables naming and the logic.

### CODE REVIEW

**Comment by arthuro555** [comment]
On the extension and examples repository, we handle things differently than on the main repository. On the main one, PRs are expected so that 4ian can review them. Here though, we can push directly on main without having a PR with 4ians approval. Once you have accepted an extension, you can push your commit directly instead of making a PR. This had been decided to allow the workload of 4ian (and probably yours too now) to be reduced.

**Comment by ClementPasteau** [comment]
Thanks for the feedback @arthuro555 - I didn't know that :)

As this is the first time I'm merging on those repositories, I wanted a quick review to make sure I wan't missing something obvious! I'll push directly moving forward

**Comment by arthuro555** [comment]
> I wanted a quick review to make sure I wasn't missing something obvious

Everything looks fine to me:
- [X] Header regenerated
- [X] File name same es internal extension name
- [X] All check passed

And I trust you have checked before making the PR that the extension is working and respects the best practices.

**Comment by 4ian** [comment]
Thanks both!

**Pull request merged**
