### PR TITLE
Update extension: Record 

### PR DESCRIPTION
**Pull request by Add00**
### Description
I've updated the extension with some new features and some bug fixes as well. Such as GIF format support. This should also resolve the issue the user on the [forums ](https://forum.gdevelop.io/t/recording-doesnt-work/44512?u=arthuro555) was having.

### How to use the extension
The same instructions apply as in the [Original PR](https://github.com/GDevelopApp/GDevelop-extensions/pull/381). This update should mostly be backwards compatible.

### Example
[record-example.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/10462902/record-example.zip)

### CODE REVIEW

**Comment by tristanbob** [comment]
Thanks @Add00 for updating this powerful extension!  Here are my results from my testing:

- Recording never works on Previews inside GDevelop.  Is this expected?  If so, you should mention it in the decription.
- GIF works great!
- WEBM works great!
- OGG and MP4... seem to create WEBM files.  Am I doing something wrong?

**Comment by Add00** [comment]
Hey @tristanbob thank your for taking the time to look at the extension. I've addressed your concerns below:

> Recording never works on Previews inside GDevelop. Is this expected? If so, you should mention it in the description.

Hmmm it should work within previews. Make sure that the file location is set using the FileSystem object, for example FileSystem::DesktopPath(). I'll update the description to make that more clear.

> OGG and MP4... seem to create WEBM files. Am I doing something wrong?

Nothings wrong, if the recording environment (Electron, Chrome, Firefox, etc) does not support that format it will deafult to a more supported format which in most cases is webm.

**Comment by tristanbob** [comment]
@D8H what should we do about these CircleCI errors?

**Comment by D8H** [comment]
> @D8H what should we do about these CircleCI errors?

It's JavaScript usage that must be declared in ExtensionsValidatorExceptions.js
It's what packaged library usually use.

**Comment by tristanbob** [comment]
> > @D8H what should we do about these CircleCI errors?
> 
> It's JavaScript usage that must be declared in ExtensionsValidatorExceptions.js It's what packaged library usually use.

Let me know if I did this right; at least CI seems to think so! :)

**Comment by D8H** [comment]
@Add00 It seems you used your old branch to update the extension. Please rebase it on the last commit of master.

**Pull request closed without merging**
