### PR TITLE
[MarchingSquare] Fix "is inside", add line drawing, add hitboxes generation.

### PR DESCRIPTION
**Pull request by D8H**
## Changes

Fixes
* "is inside" condition is more accurate
* Scalar fields are less likely to have infinity values

New features:
* Draw lines in the field
* Generate hit-boxes that can be used with the Platformer extension
  It needs these PR to work correctly: 
  * https://github.com/4ian/GDevelop/pull/3236
  * https://github.com/4ian/GDevelop/pull/3009

I can make the hit-boxes generation private because it feels buggy with the version 121 of GDevelop. Also it won't scale without a change in RuntimObject to get only the hitboxes from a given area.

## Examples
* A QIX remake
  * Build: https://d8h.itch.io/quick-impulse-xpansion
  * Project: https://www.dropbox.com/s/be9uqvf3dwi18ar/QIX.zip?dl=1

* A dynamical platform demo
  * Build: https://d8h.itch.io/destructable-platformer-demo
  * Project: https://www.dropbox.com/s/3wtwllti5ei6b0p/MarchingSquaresPlatformer.zip?dl=1

## Code to review

Why does `ShapePainterRuntimeObject` override the dimension getters?
```JavaScript
    getWidth(): float {
      return 32;
    }

    getHeight(): float {
      return 32;
    }
```
I have to make it back like it is in `RuntimeObject`.

This code is at the end of onCreate.
```JavaScript
    /**
     * Update the field hitboxes
     * @param minX {integer} left
     * @param minY {integer} top
     * @param maxX {integer} right
     * @param maxY {integer} bottom
     */
    prototype.updateMarchingSquareHitboxes = function (
      minX,
      minY,
      maxX,
      maxY
    ) {
      /** @type {boolean} */
      const drawUnder = this._getFillOutside();

      /** @type {Array<number[]>} */
      const fieldValues = this.scalarFieldValues;

      const point = this.workingPoint;

      /** @type {gdjs.ShapePainterRuntimeObject} */
      const shapePainter = this.owner;

      // Move all Polygons to recycledPolygons
      if (this.recycledPolygons.length < shapePainter._defaultHitBoxes.length) {
        const swapPolygons = this.recycledPolygons;
        this.recycledPolygons = shapePainter._defaultHitBoxes;
        shapePainter._defaultHitBoxes = swapPolygons;
      }
      const hitboxes = shapePainter._defaultHitBoxes;
      this.recycledPolygons.push.apply(this, hitboxes);
      hitboxes.length = 0;

      for (let squareY = minY; squareY < maxY - 1; squareY++) {
        for (let squareX = minX; squareX < maxX - 1; squareX++) {
          let squareIndex = this.getSquareIndex(squareX, squareY);
          if (squareIndex === 0 || squareIndex === 15) {
            continue;
          }
          if (drawUnder) {
            squareIndex = 15 - squareIndex;
          }
          let fillVertices = this.marchingSquaresFillVertices[squareIndex];
          const polygon = this.recycledPolygons.length === 0 ? new gdjs.Polygon() : this.recycledPolygons.pop();
          polygon.vertices.length = fillVertices.length;
          for (let index = 0; index < fillVertices.length; index++) {
            this.calcPoint(fillVertices[index], squareX, squareY, point);
            polygon.vertices[index] = [point[0], point[1]];
          }
          hitboxes.push(polygon);
        }
      }
      shapePainter.hitBoxes = hitboxes;
      shapePainter.hitBoxesDirty = false;
      shapePainter.aabb.min[0] = this._getAreaLeftBound();
      shapePainter.aabb.min[1] = this._getAreaTopBound();
      shapePainter.aabb.max[0] = shapePainter.aabb.min[0] + this.dimX() * this._getCellWidth();
      shapePainter.aabb.max[1] = shapePainter.aabb.min[1] + this.dimY() * this._getCellHeight();

      shapePainter.width = this.dimX() * this._getCellWidth();
      shapePainter.height = this.dimY() * this._getCellHeight();
    }

    object.width = 32;
    object.height = 32;
    // TODO hack for the "separate" action that calculates a bounding disk with dimensions.
    const objectPrototype = Object.getPrototypeOf(object);
    objectPrototype.getWidth = function () {
      return this.width;
    }
    objectPrototype.getHeight = function () {
      return this.height;
    }
```

### CODE REVIEW

**Comment by arthuro555** [comment]
!rebase

**Review by arthuro555 — APPROVED** [review]
Overall looks fine to me though it is hard to review the JavaScript code when it is in a JSON string :/
From what I've seen it looks fine though and I trust you to write good code, so this has my approval.
Let's wait for the necessary PR to be merged before merging this extension though ;)

**Comment by D8H** [comment]
I added the code that builds the hitboxes which is hacky in the PR description to help reviewers.

**Comment by arthuro555** [comment]
> Why does ShapePainterRuntimeObject override the dimension getters?

I think because the painter is not supposed to be the drawn shape itself in GDevelop, but just the painter?

> ```js
> // TODO hack for the "separate" action that calculates a bounding disk with dimensions.
> const objectPrototype = Object.getPrototypeOf(object);
> objectPrototype.getWidth = function () {
>     return this.width;
> }
> objectPrototype.getHeight = function () {
>    return this.height;
> }
> ```

Maybe only override that specific instance to avoid break any other instances (and to avoid modifying the prototype which deoptimizes the javascript engine greatly)

**Comment by arthuro555** [comment]
Was this ready to merge? My last review comment was not addressed.

**Comment by D8H** [comment]
> Was this ready to merge? My last review comment was not addressed.

I think you forgot to update the status. I'll do the change soon.

**Pull request merged**
