### PR TITLE
DragCameraWithPointer with scroll limitation

### PR DESCRIPTION
**Pull request by fishme**
### Updates

New behaviour for the "DragCameraWithPointer" extension.
Added the possibility to add it for top, bottom, left and right limitation for the dragging of the camera.

### Configuration
Screenshot 2023-02-04 at 10 17 33
Screenshot 2023-02-04 at 10 17 20

### Project files
[Example App](https://github.com/fishme/DragCameraWithPointer_Demo_Limitation)

### CODE REVIEW

**Comment by D8H** [comment]
Thank you for submitting an extension update.

Did you try to call this action after the "drag camera" action? Was there any issue?

image

**Comment by fishme** [comment]
I added into my demo repo an example with your question. There is not an error, but the behaviour isn't different to my change of 

Screenshot 2023-02-05 at 06 15 49


https://github.com/fishme/DragCameraWithPointer_Demo_Limitation
(see scene "without limitation and limitation by object")

**Comment by fishme** [comment]
I added into my example app https://github.com/fishme/DragCameraWithPointer_Demo_Limitation your request. There is no error, it is also working but not so smooth like with my additional behaviour. 

see scene "Enforuce camera boundaries"

**Comment by D8H** [comment]
The action must be in this order to work properly:

image

If someone else want to check @fishme example, here the link to open it with the web-app:
- https://editor.gdevelop.io/?project=https://raw.githubusercontent.com/fishme/DragCameraWithPointer_Demo_Limitation/develop/game.json

>If you want I could also adapt my action to the entry format of "Enforce camera boundaries" so that the entry mask is similar.

1 action that do the same as 2 actions give less freedom to users so I don't think it's necessary.

**Comment by fishme** [comment]
ok, up to you. From my side the full screen is jumping back, with the 2 actions. That is for the UX not good from my perspective. The behaviour for the user is different. ;)
Then I'll keep it in my project.

**Comment by D8H** [comment]
> ok, up to you. From my side the full screen is jumping back, with the 2 actions. That is for the UX not good from my perspective. The behaviour for the user is different. ;) Then I'll keep it in my project.

I don't see any jumping back. Are you sure you put the 2 actions in the right order like in the screenshot of my previous message?

**Comment by fishme** [comment]
ok the order was the issue. well ok works. Then let's remove my PR.

**Comment by D8H** [comment]
I'm closing this PR, but we love to see new contributors, keep it up.

**Pull request closed without merging**
