### PR TITLE
[Slider] Handle object transformations.

### PR DESCRIPTION
**Pull request by D8H**
Changes
* Handle cursor events according to object rotation, scale and position
* Fix the initial value when it's not 0
* Use color property type
* Define properties groups
* Define functions groups
* Add getters and setters for valueMin, valueMax and tickSpacing properties
* Change the extension and behavior description
* Fix 2 typos

Test project: https://www.dropbox.com/s/bf8i3ototgwvjqn/ShapePainterTransformationTest.zip?dl=1

### CODE REVIEW

**Comment by tristanbob** [comment]
How do I submit my suggested changes of your version?

Do I "Add more commits by pushing to the TransformableSlider branch on D8H/GDevelop-extensions"?  Do I submit PR's on your forked branch there?

Or do I accept your version, and then base my branch on the merged version and submit a PR for my branch?

**Comment by D8H** [comment]
> How do I submit my suggested changes of your version?
> 
> Do I "Add more commits by pushing to the TransformableSlider branch on D8H/GDevelop-extensions"? Do I submit PR's on your forked branch there?
> 
> Or do I accept your version, and then base my branch on the merged version and submit a PR for my branch?

It's better to merge mine when your are done with the review and rebase your PR over mine. Because, in theory, we shouldn't merge features we submitted. So, we can't both work on the same branch or we would have to find a 3rd person to review.

**Comment by Bouh** [comment]
- The track thickness have a problem
image
- The draggable/focus area seem only on the track? If I click on the red point of the image below the slider isn't focus
image

**Comment by D8H** [comment]
> * The track thickness have a problem
>     * The draggable/focus area seem only on the track? If I click on the red point of the image below the slider isn't focus
>     * The color of the track is pale/yellow-ish if not focus has happend atleast once

They're not regressions, it's how the extension from the repository works.

**Comment by Bouh** [comment]
I know, I tested both versions to compare during my review.
I blame no one. I only made a review ☺

**Comment by D8H** [comment]
> I know, I tested both versions to compare during my review. I blame no one. I only made a review ☺

I wasn't saying that it's not my fault. I was saying that it should not block a merge as this is not a new bug.

**Comment by tristanbob** [comment]
> * The track thickness have a problem
>   image
> * The draggable/focus area seem only on the track? If I click on the red point of the image below the slider isn't focus
>   image
> * The color of the track is pale/yellow-ish if not focus has happend atleast once

I tried to follow Material Design for the slider UI:
https://mui.com/components/slider/

1) Halo should become visible when the mouse enters the radius of the halo.
2) The thumb should jump to the position of a click if the click is:
- Within the length of the track 
- AND 
- Within the width of the halo

I want to update the extension to follow this logic, but perhaps not inside Davy's PR.

**Comment by Bouh** [comment]
Ok, lgtm 👍

**Pull request merged**
