### PR TITLE
New extension CameraZoom to zoom at a given speed.

### PR DESCRIPTION
**Pull request by D8H**
## Description

This extension allows to zoom a camera on a layer at a given speed. The zoom speed is configurable and allows a constant or even variable zoom speed.

### Actions

- Zoom by a factor every second

## Files v3.0.6
[Project.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8010761/Project.zip)
[Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8010762/Extension.zip)

See discussion history:
* https://github.com/GDevelopApp/GDevelop-extensions/issues/200

### CODE REVIEW

**Comment by D8H** [comment]
I can't validate it as I did the PR, but I'm ok with the current state.
I'll leave time to other reviewers to suggest changes and I'll merge it.

**Review by Bouh — APPROVED** [review]
Only one action, compared to the original plan it's a big clean :')

**Comment by Bouh** [comment]
This current PR has the same content as [this PR](https://github.com/GDevelopApp/GDevelop-extensions/pull/363).

**Comment by D8H** [comment]
> This current PR has the same content as [this PR](https://github.com/GDevelopApp/GDevelop-extensions/pull/363). Both have only one action.

I don't understand what triggered the other PR. I though it didn't have a PR because it's an old issue.
What happens?

**Comment by Elairyx7301** [comment]
The bot automatically created a PR for it after I fixed a few mistakes (mainly due to my incapability of property exporting the extension file again 😅) over in my original issue. I'm not enough experienced with GitHub so I can't say what could have caused this, maybe because you approved it or moved it to "extension approved" etc.?

https://github.com/GDevelopApp/GDevelop-extensions/issues/200#issuecomment-1030902582

**Comment by arthuro555** [comment]
It's because you edited your original post, that triggers a recreation of the PR, since it won't create a PR until an extension passing automated tests have been submitted, and the bot rechecks your file each time you edit the original post to see if it is ready for making a PR after the edit.

**Pull request merged**
