### PR TITLE
[AdvancedJump] Coyote time (built over Entropy work)

### PR DESCRIPTION
**Pull request by D8H**
This provides enhancements to platformer jump:
* Coyote time, also known as "ledge tolerance", allows players to jump even after their character is no longer touching the ground for a given amount of time. It aims to give a feeling of control to players.

It only contains coyote time for now, but any feature that uses "Allow jumping again" action will have to be integrated in this behavior to be able to handle conflicts.

Original work:
* https://github.com/GDevelopApp/GDevelop-extensions/issues/193

Upcoming feature:
* https://github.com/GDevelopApp/GDevelop-extensions/issues/142

## Example
* An example with a configuration that allows to see what happens
  https://www.dropbox.com/s/6wkvggox8zyh02w/CoyoteTimeExtensionExample.zip?dl=1

### CODE REVIEW

**Comment by Elairyx7301** [comment]
# Version 0.0.3

Hey @D8H,
I've now finally made the changes and added the functionalities from #142 to this project and extension. To be perfectly accurate, I didn't merge it but build it again from ground up because my version was not optimized and not suitable for more than one object.

## Functionalities
- Activate behavior (action)
- Change if reset on floor (action)
- Change amount of jumps (action)
- Instantly force changes (action)
- Return current jumps left (expression)

## Activate behavior
I have a "Activate behavior" (or "ApplyChanges") method in there that needs the object parameter but also has to be called every frame. This seems not very intuitive/efficient to me but I couldn't seem to find another way of getting this to work. Am I missing something?

## Additional changes
- Slight modifications to the "Coyote" scene settings for smoother gameplay
- Added a "Airjumps" scene to showcase midair jumps
- Extended extension short description
- Reworked extension description
- Added extension tags
- Updated extension version

## Merging
My "JumpAgain" behavior is currently separate from the "AdvancedJump" behavior. I would like to ask you to please take the merging for me because ~~I can trust myself screwing it up again~~ I'm unsure with the naming and descriptions so I think it'd be best if you could look over it again and make changes where you feel like it.

## Files

Project files:
[AdvancedJumps_ExtensionExampleV0.0.3.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7460140/AdvancedJumps_ExtensionExampleV0.0.3.zip)

Extension file (all behaviors):
[AdvancedJumps_ExtensionV0.0.3.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7460145/AdvancedJumps_ExtensionV0.0.3.json.zip)

\- Mainly for reference -
AirJumps extension file (added behavior, separate):
[AirJumps_ExtensionV0.0.3.json.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7460149/AirJumps_ExtensionV0.0.3.json.zip)

**Comment by 4ian** [comment]
I think you could maybe submit this as an "new" extension here: https://github.com/GDevelopApp/GDevelop-extensions/issues/new/choose

So that a Pull request is automatically made. Otherwise your message risks not being noticed (luckily I got a notification).
What do you think @arthuro555? Is updating an extension thanks to an issue something that will work? :)

**Comment by arthuro555** [comment]
Yes, updates should work iirc via new issues, and I'd recommend submitting them like that too

**Comment by Elairyx7301** [comment]
#271 Should be done. The bot just did something. Wow, I'm impressed - no idea or experience how GitHub works 😅
Sorry @4ian for mentioning you but I want to make sure that someone sees this :)
Please mention me if anything is missing or not optimal.

**Pull request merged**
